version: '3.1'

services:

  mongo:
    image: mongo
    volumes: 
      - ./mongodbdata:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: elfoestae
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports: 
      - 27017:27017
